import '../provider/app_language_provider.dart';

class EnLangStrings {
  static const String sidebarProfile = 'PROFILE';
  static const String sidebarID = 'ID';
  static const String sidebarLanguage = 'LANGUAGE';
  static const String sidebarSelectGameLevel = 'SELECT GAME LEVEL';
}

class MultiLangStrings {
  static const Map englishStrings = {
    "Keys": "English Translation",
    "Login": "Login",
    "Signup": "Signup",
    "You don’t have an account?": "You don’t have an account?",
    "Enter your login details": "Enter your login details",
    "Email ID": "Email ID",
    "Password": "Password",
    "Log in": "Log in",
    "Forgot Password ?": "Forgot Password ?",
    "Or": "Or",
    "Continue with Facebook": "Continue with Facebook",
    "Continue with Google": "Continue with Google",
    "Forgot Password": "Forgot Password",
    "Forgot your \npassword": "Forgot your \npassword",
    "Please enter your registered\nemail id.":
        "Please enter your registered\nemail id.",
    "Send": "Send",
    "Sign Up": "Sign Up",
    "Sign Up with Social media": "Sign Up with Social media",
    "Please enter the details for signup.":
        "Please enter the details for signup.",
    "Full Name": "Full Name",
    "Mobile No.": "Mobile No.",
    "Continue": "Continue",
    "Sign In": "Sign In",
    "Already have an account?": "Already have an account?",
    "OTP Verification": "OTP Verification",
    "OTP": "OTP",
    "Please enter the OTP sent on your Number.":
        "Please enter the OTP sent on your Number.",
    "Resend": "Resend",
    "Resend in": "Resend in",
    "Submit": "Submit",
    "Change Password": "Change Password",
    "Save": "Save",
    "Old Password": "Old Password",
    "Enter New Password": "Enter New Password",
    "Confirm New Password": "Confirm New Password",
    "Edit Profile": "Edit Profile",
    "Your profile has been updated successfully":
        "Your profile has been updated successfully",
    "Email": "Email",
    "Enter Date of Birth": "Enter Date of Birth",
    "DOB": "DOB",
    "Privacy Policy": "Privacy Policy",
    "Registration Success": "Registration Success",
    "Thank you for registration admin will\ncheck your details and back to you within 5 business day":
        "Thank you for registration admin will\ncheck your details and back to you within 5 business day",
    "Ok": "Ok",
    "Driver is on their way": "Driver is on their way",
    "Driver is arrived to pickup location":
        "Driver is arrived to pickup location",
    "Your Ride Started": "Your Ride Started",
    "Your Otp": "Your Otp",
    "Reviews": "Reviews",
    "Cancel Trip": "Cancel Trip",
    "Payment Summary": "Payment Summary",
    "Picked Up From": "Picked Up From",
    "Destination": "Destination",
    "Place your Bid": "Place your Bid",
    "You can accept suggested price below or select a lower or higher price.":
        "You can accept suggested price below or select a lower or higher price.",
    "FCFA": "FCFA",
    "Suggested Price": "Suggested Price",
    "Higher prices increase the chances of your ride being accepted.":
        "Higher prices increase the chances of your ride being accepted.",
    "Lower prices are more likely to result in the ride not being accepted.":
        "Lower prices are more likely to result in the ride not being accepted.",
    "Price variation should be at most 20% of the ride amount. Please enter a price within this range.":
        "Price variation should be at most 20% of the ride amount. Please enter a price within this range.",
    "Schedule Ride": "Schedule Ride",
    "Select Date": "Select Date",
    "Date": "Date",
    "Select Time": "Select Time",
    "Please select a time at least 4 hours later than the current time.":
        "Please select a time at least 4 hours later than the current time.",
    "Time": "Time",
    "Select Seat": "Select Seat",
    "Select 1 or more...": "Select 1 or more...",
    "Next": "Next",
    "Please select schedule date and time":
        "Please select schedule date and time",
    "Where to?": "Where to?",
    "Set your Destination": "Set your Destination",
    "Enter your Pick up and drop off location":
        "Enter your Pick up and drop off location",
    "Confirm Destination": "Confirm Destination",
    "Pin Location On Map": "Pin Location On Map",
    "My Current Location": "My Current Location",
    "Search here": "Search here",
    "Select Payment Method": "Select Payment Method",
    "Payment Methods": "Payment Methods",
    "Available": "Available",
    "Select the type of ride": "Select the type of ride",
    "Private": "Private",
    "Hourly": "Hourly",
    "Shared": "Shared",
    "Choose number of hours.": "Choose number of hours.",
    "Select Option": "Select Option",
    "Immediate": "Immediate",
    "Schedule": "Schedule",
    "Choose the vehicle": "Choose the vehicle",
    "Current Location": "Current Location",
    "Detecting location...": "Detecting location...",
    "Confirm": "Confirm",
    "Currently Not Available.": "Currently Not Available.",
    "minutes away": "minutes away",
    "Please Wait.....": "Please Wait.....",
    "Searching driver nearby you": "Searching driver nearby you",
    "Drivers did not responded.": "Drivers did not responded.",
    "The drivers might be busy doing other jobs":
        "The drivers might be busy doing other jobs",
    "Check Driver's Bid": "Check Driver's Bid",
    "Try Again": "Try Again",
    "Cancel Booking": "Cancel Booking",
    "Contacting Drivers Nearby...": "Contacting Drivers Nearby...",
    "My Routes": "My Routes",
    "Pickup Location": "Pickup Location",
    "Drop Location": "Drop Location",
    "Driver asked me to cancel": "Driver asked me to cancel",
    "Driver not getting closer": "Driver not getting closer",
    "Waiting time was too long": "Waiting time was too long",
    "Driver arrived early": "Driver arrived early",
    "Could not find driver": "Could not find driver",
    "Other": "Other",
    "Requested wrong vehicle": "Requested wrong vehicle",
    "Requested by accident": "Requested by accident",
    "Selected wrong dropoff": "Selected wrong dropoff",
    "Selected wrong pickup": "Selected wrong pickup",
    "Cancel Ride?": "Cancel Ride?",
    "Why do you want to cancel?": "Why do you want to cancel?",
    "Add bank details": "Add bank details",
    "Bank Name": "Bank Name",
    "Account Number": "Account Number",
    "Account Holder Name": "Account Holder Name",
    "Bank Branch": "Bank Branch",
    "Booking Details": "Booking Details",
    "Running": "Running",
    "Scheduled on :-": "Scheduled on :-",
    "ID": "ID",
    "Route Details:": "Route Details:",
    "Your Driver:": "Your Driver:",
    "Rate": "Rate",
    "Rating From Driver:": "Rating From Driver:",
    "Ride Amount:": "Ride Amount:",
    "Service Fees": "Service Fees",
    "Total Amount:": "Total Amount:",
    "Back to home": "Back to home",
    "Rate Driver!": "Rate Driver!",
    "Your rating is most valuable for other users":
        "Your rating is most valuable for other users",
    "Type here...": "Type here...",
    "Skip": "Skip",
    "Pending": "Pending",
    "Accepted": "Accepted",
    "Reached To Pickup": "Reached To Pickup",
    "Ride Started": "Ride Started",
    "Destination Reached": "Destination Reached",
    "Ride Completed": "Ride Completed",
    "Cancelled By User": "Cancelled By User",
    "No One Responded": "No One Responded",
    "Contact us": "Contact us",
    "How we can help you?": "How we can help you?",
    "Please enter your questions or comments here.":
        "Please enter your questions or comments here.",
    "Please provide at least 20 characters in your questions.":
        "Please provide at least 20 characters in your questions.",
    "Type a message...": "Type a message...",
    "Driver bid on": "Driver bid on",
    "Booking ID:": "Booking ID:",
    "Pickup Time:-": "Pickup Time:-",
    "Pickup": "Pickup",
    "Driver Bid Amount:": "Driver Bid Amount:",
    "Total Amount To Pay :": "Total Amount To Pay :",
    "Accept": "Accept",
    "Reject": "Reject",
    "Please double tap to exit app": "Please double tap to exit app",
    "All available": "All available",
    "Booking of Seats :-": "Booking of Seats :-",
    "Cancel": "Cancel",
    "Amount :": "Amount :",
    "Scheduled Ride": "Scheduled Ride",
    "Account suspended. Contact us at support@holebtechnologies.com for assistance.":
        "Account suspended. Contact us at support@holebtechnologies.com for assistance.",
    "You have created an account as a driver app with this credentials, you cannot log in here. Please try again with different credentials":
        "You have created an account as a driver app with this credentials, you cannot log in here. Please try again with different credentials",
    "An account already exists with that email.":
        "An account already exists with that email.",
    "An account already exists with that number.":
        "An account already exists with that number.",
    "You need to verify your number to proceed.":
        "You need to verify your number to proceed.",
    "You have entered an incorrect otp.": "You have entered an incorrect otp.",
    "You have entered an Invalid Phone Number.":
        "You have entered an Invalid Phone Number.",
    "Otp Field Cannot be empty": "Otp Field Cannot be empty",
    "Otp should be of 6 characters": "Otp should be of 6 characters",
    "We have sent you a password reset link":
        "We have sent you a password reset link",
    "Bank Added Successfully": "Bank Added Successfully",
    "Bank Edited Successfully": "Bank Edited Successfully",
    "Coming soon": "Coming soon",
    "Required**": "Required**",
    "Some Error, please update from store":
        "Some Error, please update from store",
    "No Driver available at the moment": "No Driver available at the moment",
    "A disruption was detected.": "A disruption was detected.",
    "No account created. Please Signup first":
        "No account created. Please Signup first",
    "The otp could not be verified!": "The otp could not be verified!",
    "Login session expired, you must log in again":
        "Login session expired, you must log in again",
    "Your account request is rejected by admin":
        "Your account request is rejected by admin",
    "The password provided is too weak.": "The password provided is too weak.",
    "We have sent email verification link to emailId@gmail.com. It will be automatically updated once you verify the email":
        "We have sent email verification link to emailId@gmail.com. It will be automatically updated once you verify the email",
    "Email not recognized. Please check and try again.":
        "Email not recognized. Please check and try again.",
    "Your password has been successfully changed.":
        "Your password has been successfully changed.",
    "The current password you entered is incorrect.":
        "The current password you entered is incorrect.",
    "Thank you for contacting us! We’ll get back to you within 24 hours.":
        "Thank you for contacting us! We’ll get back to you within 24 hours.",
    "Path is not drawn": "Path is not drawn",
    "Invalid credentials.": "Invalid credentials.",
    "You've Been Rated": "You've Been Rated",
    "Your passenger has rated you 5.0 for booking #123456":
        "Your passenger has rated you 5.0 for booking #123456",
    "Bid Accepted": "Bid Accepted",
    "Your bid has been accepted. and Your booking has been scheduled at 12 AUG 2023":
        "Your bid has been accepted. and Your booking has been scheduled at 12 AUG 2023",
    "Chat Started": "Chat Started",
    "CUSTOMER_NAME has started messaging you regarding booking #bookingId.":
        "CUSTOMER_NAME has started messaging you regarding booking #bookingId.",
    "Fill details to complete your account":
        "Fill details to complete your account",
    "Please enter vehicle details.": "Please enter vehicle details.",
    "Vehicle Number": "Vehicle Number",
    "License Number": "License Number",
    "Insurance Number": "Insurance Number",
    "Choose Vehicle Type": "Choose Vehicle Type",
    "Vehicle Modal": "Vehicle Modal",
    "Upload License": "Upload License",
    "Please select Image": "Please select Image",
    "Take a picture": "Take a picture",
    "Gallery": "Gallery",
    "Close": "Close",
    "Logout": "Logout",
    "Are you sure?": "Are you sure?",
    "You want to Logout": "You want to Logout",
    "Bank details not found. Please add your bank details to proceed.":
        "Bank details not found. Please add your bank details to proceed.",
    "No Data Found": "No Data Found",
    "Ride Settings": "Ride Settings",
    "Set your ride types": "Set your ride types",
    "Set your ride route": "Set your ride route",
    "Update": "Update",
    "Please enter start point": "Please enter start point",
    "Please enter end point": "Please enter end point",
    "Updated successfully": "Updated successfully",
    "Booking Accepted": "Booking Accepted",
    "Drop At": "Drop At",
    "Complete Ride": "Complete Ride",
    "Total customer need to pay:": "Total customer need to pay:",
    "Your Earning:": "Your Earning:",
    "Cash Received": "Cash Received",
    "Enter The OTP provided by rider.": "Enter The OTP provided by rider.",
    "Please enter the otp": "Please enter the otp",
    "Please enter the correct 6 digit otp":
        "Please enter the correct 6 digit otp",
    "Please enter the correct otp.": "Please enter the correct otp.",
    "Searching rides nearby you....": "Searching rides nearby you....",
    "Route": "Route",
    "Place Bid": "Place Bid",
    "Accept trip by accident": "Accept trip by accident",
    "Problem with pickup route": "Problem with pickup route",
    "Made a wrong turn": "Made a wrong turn",
    "Pickup isn't worth it": "Pickup isn't worth it",
    "Not safe to pick up": "Not safe to pick up",
    "Vehicle issue": "Vehicle issue",
    "Unaccompanied minor": "Unaccompanied minor",
    "Rider isn't here": "Rider isn't here",
    "Wrong address shown": "Wrong address shown",
    "Don't charge rider": "Don't charge rider",
    "Rider ask to cancel": "Rider ask to cancel",
    "To many riders": "To many riders",
    "To much luggage": "To much luggage",
    "No car seat": "No car seat",
    "IBAN (International Bank Account Number)":
        "IBAN (International Bank Account Number)",
    "BIC Code": "BIC Code",
    "Bank Details": "Bank Details",
    "IBAN": "IBAN",
    "No": "No",
    "Yes": "Yes",
    "Bank Name:": "Bank Name:",
    "BIC CODE:": "BIC CODE:",
    "Your Rider:": "Your Rider:",
    "Rating From Customer:": "Rating From Customer:",
    "Service Fee paid by customer (SERVICE_FEE%):":
        "Service Fee paid by customer (SERVICE_FEE%):",
    "Admin Commission (ADMIN_COMMISSION%):":
        "Admin Commission (ADMIN_COMMISSION%):",
    "Note :- Admin commission and service fee have been deducted from your wallet because the customer paid you directly in cash.":
        "Note :- Admin commission and service fee have been deducted from your wallet because the customer paid you directly in cash.",
    "TOTAL_TRIP_NUMBER trips completed": "TOTAL_TRIP_NUMBER trips completed",
    "Today": "Today",
    "Last Trip": "Last Trip",
    "GO": "GO",
    "earnings": "earnings",
    "You're offline": "You're offline",
    "My Profile": "My Profile",
    "Vehicle Details": "Vehicle Details",
    "Vehicle Model": "Vehicle Model",
    "Vehicle Type:": "Vehicle Type:",
    "Documents:-": "Documents:-",
    "Driving Licence": "Driving Licence",
    "Upload Driving License": "Upload Driving License",
    "Vehicle Registration": "Vehicle Registration",
    "Upload Registration": "Upload Registration",
    "My Earnings": "My Earnings",
    "Total Earnings": "Total Earnings",
    "Withdrawal": "Withdrawal",
    "Add Bank": "Add Bank",
    "Transations": "Transations",
    "Notifications": "Notifications",
    "Clear All": "Clear All",
    "Withdraw Request": "Withdraw Request",
    "Bank Not Added": "Bank Not Added",
    "Your account balance is below the minimum withdrawal limit of WITHDRAW_LIMIT_PRICE":
        "Your account balance is below the minimum withdrawal limit of WITHDRAW_LIMIT_PRICE",
    "Rejected Reason :-": "Rejected Reason :-",
    "Create New Request": "Create New Request",
    "Please fill the details to create a new withdraw request":
        "Please fill the details to create a new withdraw request",
    "Enter your amount": "Enter your amount",
    "Enter Amount": "Enter Amount",
    "Amount should be less then balance.":
        "Amount should be less then balance.",
    "Select Account": "Select Account",
    "You are not near the pickup location. Please proceed to the pickup location.":
        "You are not near the pickup location. Please proceed to the pickup location.",
    "Thank you! Your withdrawal request has been submitted successfully. It’s in pending state. Generally it takes 2-3 busniess days.":
        "Thank you! Your withdrawal request has been submitted successfully. It’s in pending state. Generally it takes 2-3 busniess days.",
    "Your bid has been placed successfully":
        "Your bid has been placed successfully",
    "Please give access!": "Please give access!",
    "Password reset link has been sent to your email":
        "Password reset link has been sent to your email",
    "Email not found": "Email not found",
    "Your current password is incorrect.":
        "Your current password is incorrect.",
    "Ride History": "Ride History",
    "Past Booking": "Past Booking",
    "Current Booking": "Current Booking",
    "Scheduled": "Scheduled",
    "Completed": "Completed",
    "Please enter your password to continue":
        "Please enter your password to continue",
    "Enter location...": "Enter location...",
    "Your booking has been scheduled.": "Your booking has been scheduled.",
    "Your booking has been accepted by captain DRIVER_NAME. Captain will arrived soon.":
        "Your booking has been accepted by captain DRIVER_NAME. Captain will arrived soon.",
    "Your ride has been started. Enjoy your ride with captain DRIVER_NAME":
        "Your ride has been started. Enjoy your ride with captain DRIVER_NAME",
    "Your ride has been completed.": "Your ride has been completed.",
    "DRIVER_NAME has arrived at your pickup location. Please meet your captian at the pickup point.":
        "DRIVER_NAME has arrived at your pickup location. Please meet your captian at the pickup point.",
    "Meet Your Captian": "Meet Your Captian",
    "You have arrived at the pickup location. Please wait for the passenger and contact them":
        "You have arrived at the pickup location. Please wait for the passenger and contact them",
    "Meet Your Passenger": "Meet Your Passenger",
    "Your driver has arrived at the drop-off location. Please proceed to your destination.":
        "Your driver has arrived at the drop-off location. Please proceed to your destination.",
    "You have reached the destination. Please inform the passenger.":
        "You have reached the destination. Please inform the passenger.",
    "Start Ride": "Start Ride",
    "Rate Customer!": "Rate Customer!",
    "A new booking request has arrived in your nearby location":
        "A new booking request has arrived in your nearby location",
    "Please allow location permission to access the app's functionality. Without this permission, the app cannot operate properly. Please open the app settings to allow this permission.":
        "Please allow location permission to access the app's functionality. Without this permission, the app cannot operate properly. Please open the app settings to allow this permission.",
    "Allow": "Permettre",
    "Your driver has rated you for booking #12345":
        "Your driver has rated you for booking #12345",
  };

  static const Map frenchStrings = {
    "Keys": "French Translation",
    "Login": "Connexion",
    "Signup": "Inscription",
    "You don’t have an account?": "Vous n'avez pas de compte ?",
    "Enter your login details": "Entrez vos identifiants",
    "Email ID": "Identifiant Email",
    "Password": "Mot de passe",
    "Log in": "Se connecter",
    "Forgot Password ?": "Mot de passe oublié ?",
    "Or": "Ou",
    "Continue with Facebook": "Continuer avec Facebook",
    "Continue with Google": "Continuer avec Google",
    "Forgot Password": "Mot de passe oublié",
    "Forgot your \npassword": "\"Mot de passe oublié\"",
    "Please enter your registered\nemail id.":
        "\"Veuillez entrer votre adresse e-mail enregistrée.\"",
    "Send": "Envoyer",
    "Sign Up": "S'inscrire",
    "Sign Up with Social media": "Inscrivez-vous avec les réseaux sociaux",
    "Please enter the details for signup.":
        "Veuillez entrer les détails pour vous inscrire.",
    "Full Name": "Nom complet",
    "Mobile No.": "Numéro de mobile",
    "Continue": "Continuer",
    "Sign In": "Se connecter",
    "Already have an account?": "Vous avez déjà un compte ?",
    "OTP Verification": "Vérification OTP",
    "OTP": "OTP",
    "Please enter the OTP sent on your Number.":
        "Veuillez entrer l'OTP envoyé sur votre numéro.",
    "Resend": "Renvoyer",
    "Resend in": "Renvoyer dans",
    "Submit": "Soumettre",
    "Change Password": "Changer le mot de passe",
    "Save": "Sauvegarder",
    "Old Password": "Ancien mot de passe",
    "Enter New Password": "Entrez un nouveau mot de passe",
    "Confirm New Password": "Confirmez le nouveau mot de passe",
    "Edit Profile": "Modifier le profil",
    "Your profile has been updated successfully":
        "Votre profil a été mis à jour avec succès",
    "Email": "Email",
    "Enter Date of Birth": "Entrez votre date de naissance",
    "DOB": "DDN",
    "Privacy Policy": "Politique de confidentialité",
    "Registration Success": "Inscription réussie",
    "Thank you for registration admin will\ncheck your details and back to you within 5 business day":
        "\"Merci pour votre inscription, l'administrateur vérifiera vos détails et vous répondra sous 5 jours ouvrables\"",
    "Ok": "Ok",
    "Driver is on their way": "Le chauffeur est en route",
    "Driver is arrived to pickup location":
        "Le chauffeur est arrivé au lieu de prise en charge",
    "Your Ride Started": "Votre trajet a commencé",
    "Your Otp": "Votre OTP",
    "Reviews": "Avis",
    "Cancel Trip": "Annuler le trajet",
    "Payment Summary": "Résumé du paiement",
    "Picked Up From": "Pris en charge de",
    "Destination": "Destination",
    "Place your Bid": "Miser",
    "You can accept suggested price below or select a lower or higher price.":
        "Vous pouvez accepter le prix suggéré ci-dessous ou sélectionner un prix plus bas ou plus élevé.",
    "FCFA": "FCFA",
    "Suggested Price": "Prix suggéré",
    "Higher prices increase the chances of your ride being accepted.":
        "Des prix plus élevés augmentent les chances que votre trajet soit accepté.",
    "Lower prices are more likely to result in the ride not being accepted.":
        "Des prix plus bas risquent de ne pas faire accepter le trajet.",
    "Price variation should be at most 20% of the ride amount. Please enter a price within this range.":
        "La variation de prix doit être au maximum de 20 % du montant du trajet. Veuillez entrer un prix dans cette fourchette.",
    "Schedule Ride": "Programmer un trajet",
    "Select Date": "Sélectionner une date",
    "Date": "Date",
    "Select Time": "Sélectionner une heure",
    "Please select a time at least 4 hours later than the current time.":
        "Veuillez sélectionner une heure au moins 4 heures après l'heure actuelle.",
    "Time": "Heure",
    "Select Seat": "Choisir une place",
    "Select 1 or more...": "Choisir 1 ou plus...",
    "Next": "Suivant",
    "Please select schedule date and time":
        "Veuillez choisir la date et l'heure programmées",
    "Where to?": "Où vous allez ?",
    "Set your Destination": "Définir votre destination",
    "Enter your Pick up and drop off location":
        "Entrez votre lieu de prise en charge et de dépose",
    "Confirm Destination": "Confirmer la destination",
    "Pin Location On Map": "Épingler l'emplacement sur la carte",
    "My Current Location": "Ma position actuelle",
    "Search here": "Rechercher ici",
    "Select Payment Method": "Sélectionner le mode de paiement",
    "Payment Methods": "Méthodes de paiement",
    "Available": "Disponible",
    "Select the type of ride": "Sélectionner le type de trajet",
    "Private": "Privé",
    "Hourly": "A l'heure",
    "Shared": "Partagé",
    "Choose number of hours.": "Choisir le nombre d'heures.",
    "Select Option": "Sélectionner une option",
    "Immediate": "Immédiat",
    "Schedule": "Programmer",
    "Choose the vehicle": "Choisir le véhicule",
    "Current Location": "Position actuelle",
    "Detecting location...": "Détection de l'emplacement...",
    "Confirm": "Confirmer",
    "Currently Not Available.": "Actuellement non disponible.",
    "minutes away": "minutes d'attente",
    "Please Wait.....": "Veuillez patienter.....",
    "Searching driver nearby you": "Recherche de chauffeur à proximité de vous",
    "Drivers did not responded.": "Les chauffeurs n'ont pas répondu.",
    "The drivers might be busy doing other jobs":
        "Les chauffeurs sont peut-être déjà en courses",
    "Check Driver's Bid": "Consulter l'offre du chauffeur",
    "Try Again": "Réessayer",
    "Cancel Booking": "Annuler la réservation",
    "Contacting Drivers Nearby...": "Recherche des chauffeurs à proximité...",
    "My Routes": "Mes itinéraires",
    "Pickup Location": "Lieu de prise en charge",
    "Drop Location": "Lieu de dépose",
    "Driver asked me to cancel": "Le chauffeur m'a demandé d'annuler",
    "Driver not getting closer": "Le chauffeur ne se rapproche pas",
    "Waiting time was too long": "Le temps d'attente était trop long",
    "Driver arrived early": "Le chauffeur est arrivé en avance",
    "Could not find driver": "Impossible de trouver le chauffeur",
    "Other": "Autre",
    "Requested wrong vehicle": "Véhicule demandé par erreur",
    "Requested by accident": "Demande effectuée par accident",
    "Selected wrong dropoff": "Dépose sélectionnée incorrectement",
    "Selected wrong pickup": "Prise en charge sélectionnée incorrectement",
    "Cancel Ride?": "Annuler le trajet ?",
    "Why do you want to cancel?": "Pourquoi voulez-vous annuler ?",
    "Add bank details": "Ajouter les détails bancaires",
    "Bank Name": "Nom de la banque",
    "Account Number": "Numéro de compte",
    "Account Holder Name": "Nom du titulaire du compte",
    "Bank Branch": "Agence bancaire",
    "Booking Details": "Détails de la réservation",
    "Running": "En cours",
    "Scheduled on :-": "Programmé le :-",
    "ID": "ID",
    "Route Details:": "Détails de l'itinéraire :",
    "Your Driver:": "Votre chauffeur :",
    "Rate": "Noter",
    "Rating From Driver:": "Note du chauffeur :",
    "Ride Amount:": "Montant du trajet :",
    "Service Fees": "Frais de service",
    "Total Amount:": "Montant total :",
    "Back to home": "Retour à l'accueil",
    "Rate Driver!": "Noter le chauffeur !",
    "Your rating is most valuable for other users":
        "Votre note est très précieuse pour les autres utilisateurs",
    "Type here...": "Tapez ici...",
    "Skip": "Passer",
    "Pending": "En attente",
    "Accepted": "Accepté",
    "Reached To Pickup": "Arrivé au lieu de prise en charge",
    "Ride Started": "Trajet commencé",
    "Destination Reached": "Destination atteinte",
    "Ride Completed": "Trajet terminé",
    "Cancelled By User": "Annulé par l'utilisateur",
    "No One Responded": "Personne n'a répondu",
    "Contact us": "Contactez-nous",
    "How we can help you?": "Comment pouvons-nous vous aider ?",
    "Please enter your questions or comments here.":
        "Veuillez entrer vos questions ou commentaires ici.",
    "Please provide at least 20 characters in your questions.":
        "Veuillez fournir au moins 20 caractères dans vos questions.",
    "Type a message...": "Tapez un message...",
    "Driver bid on": "Offre du chauffeur",
    "Booking ID:": "ID de réservation :",
    "Pickup Time:-": "Heure de prise en charge :-",
    "Pickup": "Prise en charge",
    "Driver Bid Amount:": "Montant de l'offre du chauffeur :",
    "Total Amount To Pay :": "Montant total à payer :",
    "Accept": "Accepter",
    "Reject": "Rejeter",
    "Please double tap to exit app":
        "Veuillez appuyer deux fois pour quitter l'application",
    "All available": "Tout disponible",
    "Booking of Seats :-": "Réservation de places :-",
    "Cancel": "Annuler",
    "Amount :": "Montant :",
    "Scheduled Ride": "Trajet programmé",
    "Account suspended. Contact us at support@holebtechnologies.com for assistance.":
        "Compte suspendu. Contactez-nous à support@holebtechnologies.com pour obtenir de l'aide.",
    "You have created an account as a driver app with this credentials, you cannot log in here. Please try again with different credentials":
        "Vous avez créé un compte en tant que chauffeur avec ces identifiants, vous ne pouvez pas vous connecter ici. Veuillez réessayer avec des identifiants différents",
    "An account already exists with that email.":
        "Un compte existe déjà avec cet e-mail.",
    "An account already exists with that number.":
        "Un compte existe déjà avec ce numéro.",
    "You need to verify your number to proceed.":
        "Vous devez vérifier votre numéro pour continuer.",
    "You have entered an incorrect otp.": "Vous avez entré un otp incorrect.",
    "You have entered an Invalid Phone Number.":
        "Vous avez entré un numéro de téléphone non valide.",
    "Otp Field Cannot be empty": "Le champ OTP ne peut pas être vide",
    "Otp should be of 6 characters": "L'otp doit comporter 6 caractères",
    "We have sent you a password reset link":
        "Nous vous avons envoyé un lien de réinitialisation du mot de passe",
    "Bank Added Successfully": "Banque ajoutée avec succès",
    "Bank Edited Successfully": "Banque modifiée avec succès",
    "Coming soon": "Bientôt disponible",
    "Required**": "Requis**",
    "Some Error, please update from store":
        "Une erreur s'est produite, veuillez mettre à jour depuis le store",
    "No Driver available at the moment":
        "Aucun chauffeur disponible pour le moment",
    "A disruption was detected.": "Une perturbation a été détectée.",
    "No account created. Please Signup first":
        "Aucun compte créé. Veuillez d'abord vous inscrire",
    "The otp could not be verified!": "L'otp n'a pas pu être vérifié !",
    "Login session expired, you must log in again":
        "Session expirée, vous devez vous reconnecter",
    "Your account request is rejected by admin":
        "Votre demande de compte a été rejetée par l'administrateur",
    "The password provided is too weak.":
        "Le mot de passe fourni est trop faible.",
    "We have sent email verification link to emailId@gmail.com. It will be automatically updated once you verify the email":
        "Nous vous avons envoyé un lien de vérification par e-mail à emailId@gmail.com. Il sera automatiquement mis à jour une fois que vous aurez vérifié l'e-mail",
    "Email not recognized. Please check and try again.":
        "E-mail non reconnu. Veuillez vérifier et réessayer.",
    "Your password has been successfully changed.":
        "Votre mot de passe a été changé avec succès.",
    "The current password you entered is incorrect.":
        "Le mot de passe actuel que vous avez entré est incorrect.",
    "Thank you for contacting us! We’ll get back to you within 24 hours.":
        "Merci de nous avoir contactés ! Nous vous répondrons dans les 24 heures.",
    "Path is not drawn": "Le chemin n'est pas tracé",
    "Invalid credentials.": "Identifiants invalides.",
    "You've Been Rated": "Vous avez été noté",
    "Your passenger has rated you 5.0 for booking #123456":
        "Votre passager vous a noté 5.0 pour la réservation #123456",
    "Bid Accepted": "Offre acceptée",
    "Your bid has been accepted. and Your booking has been scheduled at 12 AUG 2023":
        "Votre offre a été acceptée. et Votre réservation a été programmée pour le 12 AOÛT 2023",
    "Chat Started": "Discussion commencée",
    "CUSTOMER_NAME has started messaging you regarding booking #bookingId.":
        "CUSTOMER_NAME a commencé à vous envoyer des messages concernant la réservation #bookingId.",
    "Fill details to complete your account":
        "Remplissez les détails pour compléter votre compte",
    "Please enter vehicle details.": "Veuillez entrer les détails du véhicule.",
    "Vehicle Number": "Numéro de véhicule",
    "License Number": "Numéro de licence",
    "Insurance Number": "Numéro d'assurance",
    "Choose Vehicle Type": "Choisissez le type de véhicule",
    "Vehicle Modal": "Modèle du véhicule",
    "Upload License": "Télécharger la licence",
    "Please select Image": "Veuillez sélectionner une image",
    "Take a picture": "Prendre une photo",
    "Gallery": "Galerie",
    "Close": "Fermer",
    "Logout": "Déconnexion",
    "Are you sure?": "Êtes-vous sûr ?",
    "You want to Logout": "Vous voulez vous déconnecter",
    "Bank details not found. Please add your bank details to proceed.":
        "Détails bancaires introuvables. Veuillez ajouter vos coordonnées bancaires pour continuer.",
    "No Data Found": "Aucune donnée trouvée",
    "Ride Settings": "Paramètres de trajet",
    "Set your ride types": "Définir vos types de trajets",
    "Set your ride route": "Définir votre itinéraire de trajet",
    "Update": "Mettre à jour",
    "Please enter start point": "Veuillez entrer le point de départ",
    "Please enter end point": "Veuillez entrer le point d'arrivée",
    "Updated successfully": "Mis à jour avec succès",
    "Booking Accepted": "Réservation acceptée",
    "Drop At": "Déposer à",
    "Complete Ride": "Terminer le trajet",
    "Total customer need to pay:": "Montant total à payer par le client :",
    "Your Earning:": "Votre gain :",
    "Cash Received": "Espèces reçues",
    "Enter The OTP provided by rider.": "Entrez l'OTP fourni par le passager.",
    "Please enter the otp": "Veuillez entrer l'otp",
    "Please enter the correct 6 digit otp":
        "Veuillez entrer le bon otp à 6 chiffres",
    "Please enter the correct otp.": "Veuillez entrer le bon otp.",
    "Searching rides nearby you....": "Recherche de courses à proximité...",
    "Route": "Itinéraire",
    "Place Bid": "Faire une offre",
    "Accept trip by accident": "Trajet accepté par accident",
    "Problem with pickup route":
        "Problème avec l'itinéraire de prise en charge",
    "Made a wrong turn": "Fausse manœuvre",
    "Pickup isn't worth it": "La prise en charge ne vaut pas le coup",
    "Not safe to pick up": "Pas sûr de prendre en charge",
    "Vehicle issue": "Problème avec le véhicule",
    "Unaccompanied minor": "Mineur non accompagné",
    "Rider isn't here": "Le passager n'est pas là",
    "Wrong address shown": "Mauvaise adresse indiquée",
    "Don't charge rider": "Ne pas facturer le passager",
    "Rider ask to cancel": "Le passager demande d'annuler",
    "To many riders": "Trop de passagers",
    "To much luggage": "Trop de bagages",
    "No car seat": "Pas de siège auto",
    "IBAN (International Bank Account Number)":
        "IBAN (Numéro International de Compte Bancaire)",
    "BIC Code": "Code BIC",
    "Bank Details": "Détails bancaires",
    "IBAN": "IBAN",
    "No": "Non",
    "Yes": "Oui",
    "Bank Name:": "Nom de la banque :",
    "BIC CODE:": "CODE BIC :",
    "Your Rider:": "Votre passager :",
    "Rating From Customer:": "Note du client :",
    "Service Fee paid by customer (SERVICE_FEE%):":
        "Frais de service payés par le client (SERVICE_FEE%) :",
    "Admin Commission (ADMIN_COMMISSION%):": "Commission (ADMIN_COMMISSION%) :",
    "Note :- Admin commission and service fee have been deducted from your wallet because the customer paid you directly in cash.":
        "Note : - La commission et les frais de service ont été déduits de votre portefeuille car le client vous a payé directement en espèces.",
    "TOTAL_TRIP_NUMBER trips completed": "TOTAL_TRIP_NUMBER trajets terminés",
    "Today": "Aujourd'hui",
    "Last Trip": "Dernier trajet",
    "GO": "Aller",
    "earnings": "Gains",
    "You're offline": "Vous êtes hors ligne",
    "My Profile": "Mon profil",
    "Vehicle Details": "Détails du véhicule",
    "Vehicle Model": "Modèle du véhicule",
    "Vehicle Type:": "Type de véhicule :",
    "Documents:-": "Documents :-",
    "Driving Licence": "Permis de conduire",
    "Upload Driving License": "Télécharger le permis de conduire",
    "Vehicle Registration": "Immatriculation du véhicule",
    "Upload Registration": "Télécharger le certificat d'immatriculation",
    "My Earnings": "Mes gains",
    "Total Earnings": "Gains totaux",
    "Withdrawal": "Retrait",
    "Add Bank": "Ajouter une banque",
    "Transations": "Transactions",
    "Notifications": "Notifications",
    "Clear All": "Tout effacer",
    "Withdraw Request": "Demande de retrait",
    "Bank Not Added": "Banque non ajoutée",
    "Your account balance is below the minimum withdrawal limit of WITHDRAW_LIMIT_PRICE":
        "Votre solde est inférieur au montant minimum de retrait de WITHDRAW_LIMIT_PRICE",
    "Rejected Reason :-": "Raison du rejet :-",
    "Create New Request": "Créer une nouvelle demande",
    "Please fill the details to create a new withdraw request":
        "Veuillez remplir les détails pour créer une nouvelle demande de retrait",
    "Enter your amount": "Entrez votre montant",
    "Enter Amount": "Entrer le montant",
    "Amount should be less then balance.":
        "Le montant doit être inférieur au solde.",
    "Select Account": "Sélectionner un compte",
    "You are not near the pickup location. Please proceed to the pickup location.":
        "Vous n'êtes pas près du lieu de prise en charge. Veuillez vous rendre au lieu de prise en charge.",
    "Thank you! Your withdrawal request has been submitted successfully. It’s in pending state. Generally it takes 2-3 busniess days.":
        "Merci ! Votre demande de retrait a été soumise avec succès. Elle est en attente. En général, cela prend 2-3 jours ouvrables.",
    "Your bid has been placed successfully":
        "Votre offre a été placée avec succès",
    "Please give access!": "Veuillez donner accès !",
    "Password reset link has been sent to your email":
        "Un lien de réinitialisation du mot de passe a été envoyé à votre e-mail",
    "Email not found": "E-mail non trouvé",
    "Your current password is incorrect.":
        "Votre mot de passe actuel est incorrect.",
    "Ride History": "Historique des trajets",
    "Past Booking": "Réservations passées",
    "Current Booking": "Réservation en cours",
    "Scheduled": "Programmé",
    "Completed": "Terminé",
    "Please enter your password to continue":
        "Veuillez entrer votre mot de passe pour continuer",
    "Enter location...": "Entrez l'emplacement...",
    "Your booking has been scheduled.": "Votre réservation a été programmée.",
    "Your booking has been accepted by captain DRIVER_NAME. Captain will arrived soon.":
        "Votre réservation a été acceptée par le capitaine DRIVER_NAME. Le capitaine arrivera bientôt.",
    "Your ride has been started. Enjoy your ride with captain DRIVER_NAME":
        "Votre trajet a commencé. Profitez de votre trajet avec le capitaine DRIVER_NAME",
    "Your ride has been completed.": "Votre trajet est terminé.",
    "DRIVER_NAME has arrived at your pickup location. Please meet your captian at the pickup point.":
        "DRIVER_NAME est arrivé à votre lieu de prise en charge. Veuillez rejoindre votre capitaine au point de prise en charge.",
    "Meet Your Captian": "Rejoindre votre capitaine",
    "You have arrived at the pickup location. Please wait for the passenger and contact them":
        "Vous êtes arrivé à l'emplacement de prise en charge. Veuillez attendre le passager et le contacter",
    "Meet Your Passenger": "Rencontrer votre passager",
    "Your driver has arrived at the drop-off location. Please proceed to your destination.":
        "Votre chauffeur est arrivé à l'emplacement de dépose. Veuillez vous rendre à destination.",
    "You have reached the destination. Please inform the passenger.":
        "Vous êtes arrivé à destination. Veuillez informer le passager.",
    "Start Ride": "Commencer la course",
    "Rate Customer!": "Évaluer le client !",
    "A new booking request has arrived in your nearby location":
        "Une nouvelle demande de réservation est arrivée dans votre zone",
    "Please allow location permission to access the app's functionality. Without this permission, the app cannot operate properly. Please open the app settings to allow this permission.":
        "Veuillez autoriser l'accès à votre position pour utiliser les fonctionnalités de l'application. Sans cette autorisation, l'application ne pourra pas fonctionner correctement. Veuillez ouvrir les paramètres de l'application pour autoriser cette permission.",
    "Allow": "Permettre",
    "Your driver has rated you for booking #12345":
        "Votre chauffeur vous a attribué une note pour la réservation #12345",
  };
}

String translate(String key) {
  if (selectedLanguageNotifier['key'] == 'en') {
    return MultiLangStrings.englishStrings[key] ?? key;
    // (key.isEmpty ? '' : "${key}null");
  } else if (selectedLanguageNotifier['key'] == 'fr') {
    return MultiLangStrings.frenchStrings[key] ?? key;
    // (key.isEmpty ? '' : "${key}null");
  } else {
    return MultiLangStrings.frenchStrings[key] ?? key;
    // (key.isEmpty ? '' : "${key}null");
  }
}
