import 'package:connect_app_driver/constants/language_en.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import '../themes/custom_text_styles.dart';

// ignore: must_be_immutable
class CustomText extends StatelessWidget {
  String text;
  TextStyle style;
  double? fontSize;
  FontStyle? fontStyle;
  FontWeight? fontWeight;
  String? fontFamily;
  Color? color;
  Color? backgroundColor;
  double? height;
  TextOverflow? overflow;
  TextDirection? textDirection;
  TextAlign? textAlign;
  TextDecoration? decoration;
  double? decorationThickness;
  TextDecorationStyle? decorationStyle;
  Paint? backgroundPaint;
  Paint? foregroundPaint;
  String? debugLabel;
  bool? inherit;
  List<String>? fontFamilyFallback;
  List<FontFeature>? fontFeatures;
  List<FontVariation>? fontVariations;
  TextLeadingDistribution? leadingDistribution;
  double? letterSpacing;
  Locale? locale;
  String? package;
  List<Shadow>? shadows;
  TextBaseline? textBaseline;
  double? wordSpacing;

  @override
  Widget build(BuildContext context) {
    return Text(
      // text,
      translate(text),
      textAlign: textAlign,
      style: style.copyWith(
        color: color,
        fontSize: fontSize,
        fontWeight: fontWeight,
        fontStyle: fontStyle,
        fontFamily: fontFamily,
        height: height,
        decoration: decoration,
        decorationColor: color,
        decorationStyle: decorationStyle,
        background: backgroundPaint,
        backgroundColor: backgroundColor,
        debugLabel: debugLabel,
        decorationThickness: decorationThickness,
        fontFamilyFallback: fontFamilyFallback,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        foreground: foregroundPaint,
        inherit: inherit,
        leadingDistribution: leadingDistribution,
        letterSpacing: letterSpacing,
        locale: locale,
        overflow: overflow,
        package: package,
        shadows: shadows,
        textBaseline: textBaseline,
        wordSpacing: wordSpacing,
      ),
      overflow: overflow,
      textDirection: textDirection,
    );
  }

  CustomText.bodyText1(this.text,
      {super.key,
      this.style = CustomTextStyle.bodyText1,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});

  CustomText.bodyText2(this.text,
      {super.key,
      this.style = CustomTextStyle.bodyText2,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.heading(this.text,
      {super.key,
      this.style = CustomTextStyle.heading,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.headingSmall(this.text,
      {super.key,
      this.style = CustomTextStyle.headingSmall,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.headingLarge(this.text,
      {super.key,
      this.style = CustomTextStyle.headingLarge,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.appbarText(this.text,
      {super.key,
      this.style = CustomTextStyle.appbarText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.textFieldHeading(this.text,
      {super.key,
      this.style = CustomTextStyle.textFieldHeading,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.textFieldHint(this.text,
      {super.key,
      this.style = CustomTextStyle.textFieldHint,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.textFieldText(this.text,
      {super.key,
      this.style = CustomTextStyle.textFieldText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.drawerText(this.text,
      {super.key,
      this.style = CustomTextStyle.drawerText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.settingsText(this.text,
      {super.key,
      this.style = CustomTextStyle.settingsText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.smallText(this.text,
      {super.key,
      this.style = CustomTextStyle.smallText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
  CustomText.buttonText(this.text,
      {super.key,
      this.style = CustomTextStyle.buttonText,
      this.fontSize,
      this.fontStyle,
      this.fontWeight,
      this.fontFamily,
      this.color,
      this.backgroundColor,
      this.height,
      this.overflow,
      this.textDirection,
      this.textAlign,
      this.decoration,
      this.decorationThickness,
      this.decorationStyle,
      this.backgroundPaint,
      this.foregroundPaint,
      this.debugLabel,
      this.inherit,
      this.fontFamilyFallback,
      this.fontFeatures,
      this.fontVariations,
      this.leadingDistribution,
      this.letterSpacing,
      this.locale,
      this.package,
      this.shadows,
      this.textBaseline,
      this.wordSpacing});
}
